name: Build and deploy GitHub pages

on: [ workflow_call ]

permissions:
  contents: write

jobs:
  publish-gh-pages:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download badges
        uses: actions/download-artifact@v6
        with:
          name: badges-ubuntu_latest-python-3.13
          path: build

      - name: Copy index.html
        run: cp ./.github/pages/index.html build/index.html

      - name: Copy reports
        run: |
          cp ./chatgpt_proxy/cov_html/* build/reports/coverage
          cp ./chatgpt_proxy/coverage.xml build/reports/coverage

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

  purge-readme-images:
    needs: [ publish-gh-pages ]
    uses: ./.github/workflows/purge-readme-images.yml
